# Generated by Django 4.1.5 on 2023-03-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50, verbose_name='Marka')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Adı')),
                ('text', models.TextField(max_length=1000, verbose_name='Ürün Hakkında')),
                ('image', models.FileField(upload_to='', verbose_name='Ürün Fotografı')),
                ('date_now', models.DateTimeField(verbose_name='Tarih')),
                ('likes', models.FloatField(default=0, verbose_name='Ürün Beğenisi')),
                ('price', models.FloatField(default=0, verbose_name='Ürün Fiyatı')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
            ],
        ),
    ]
