# Generated by Django 4.1.5 on 2023-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_userprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='deneyim',
            field=models.IntegerField(default=0, verbose_name='Deneyim'),
        ),
    ]
