# Generated by Django 4.1.5 on 2023-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_userprofil_deneyim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='image',
            field=models.ImageField(default='img7.jfif', upload_to='', verbose_name='Profil Resmi'),
        ),
    ]
