# Generated by Django 4.1.5 on 2023-03-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_alter_userprofil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='image',
            field=models.ImageField(default='profilresmi.png', upload_to='', verbose_name='Profil Resmi'),
        ),
    ]
